// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: proto/bdrun.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_UNKNOWN          MessageType = 0
	MessageType_COMMAND_REQUEST  MessageType = 1
	MessageType_COMMAND_RESPONSE MessageType = 2
	MessageType_STDOUT_DATA      MessageType = 3
	MessageType_STDERR_DATA      MessageType = 4
	MessageType_STDIN_DATA       MessageType = 5
	MessageType_PTY_RESIZE       MessageType = 6
	MessageType_EXIT_CODE        MessageType = 7
	MessageType_ERROR            MessageType = 8
	MessageType_HEARTBEAT        MessageType = 9
	MessageType_AUTH_REQUEST     MessageType = 10
	MessageType_AUTH_RESPONSE    MessageType = 11
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "COMMAND_REQUEST",
		2:  "COMMAND_RESPONSE",
		3:  "STDOUT_DATA",
		4:  "STDERR_DATA",
		5:  "STDIN_DATA",
		6:  "PTY_RESIZE",
		7:  "EXIT_CODE",
		8:  "ERROR",
		9:  "HEARTBEAT",
		10: "AUTH_REQUEST",
		11: "AUTH_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":          0,
		"COMMAND_REQUEST":  1,
		"COMMAND_RESPONSE": 2,
		"STDOUT_DATA":      3,
		"STDERR_DATA":      4,
		"STDIN_DATA":       5,
		"PTY_RESIZE":       6,
		"EXIT_CODE":        7,
		"ERROR":            8,
		"HEARTBEAT":        9,
		"AUTH_REQUEST":     10,
		"AUTH_RESPONSE":    11,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bdrun_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_bdrun_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_bdrun_proto_rawDescGZIP(), []int{0}
}

type StreamType int32

const (
	StreamType_STREAM_UNKNOWN StreamType = 0
	StreamType_STREAM_STDOUT  StreamType = 1
	StreamType_STREAM_STDERR  StreamType = 2
	StreamType_STREAM_STDIN   StreamType = 3
)

// Enum value maps for StreamType.
var (
	StreamType_name = map[int32]string{
		0: "STREAM_UNKNOWN",
		1: "STREAM_STDOUT",
		2: "STREAM_STDERR",
		3: "STREAM_STDIN",
	}
	StreamType_value = map[string]int32{
		"STREAM_UNKNOWN": 0,
		"STREAM_STDOUT":  1,
		"STREAM_STDERR":  2,
		"STREAM_STDIN":   3,
	}
)

func (x StreamType) Enum() *StreamType {
	p := new(StreamType)
	*p = x
	return p
}

func (x StreamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bdrun_proto_enumTypes[1].Descriptor()
}

func (StreamType) Type() protoreflect.EnumType {
	return &file_proto_bdrun_proto_enumTypes[1]
}

func (x StreamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamType.Descriptor instead.
func (StreamType) EnumDescriptor() ([]byte, []int) {
	return file_proto_bdrun_proto_rawDescGZIP(), []int{1}
}

// Message envelope for all communications
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`                                               // Unique connection identifier
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`                                                                          // Message sequence number
	Type          MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=bdrun.v1.MessageType" json:"type,omitempty"`                                                        // Message type discriminator
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                                                             // Type-specific payload
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Extensible metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_bdrun_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdrun_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_bdrun_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *Message) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Command execution request
type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`                                                                   // Binary name
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`                                                                         // Arguments
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Environment variables
	WorkingDir    string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`                                           // Working directory
	AllocatePty   bool                   `protobuf:"varint,5,opt,name=allocate_pty,json=allocatePty,proto3" json:"allocate_pty,omitempty"`                                       // Request PTY allocation
	PtySize       *TerminalSize          `protobuf:"bytes,6,opt,name=pty_size,json=ptySize,proto3" json:"pty_size,omitempty"`                                                    // Initial PTY size
	StdinData     []byte                 `protobuf:"bytes,7,opt,name=stdin_data,json=stdinData,proto3" json:"stdin_data,omitempty"`                                              // Initial stdin data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_proto_bdrun_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdrun_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_bdrun_proto_rawDescGZIP(), []int{1}
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CommandRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CommandRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *CommandRequest) GetAllocatePty() bool {
	if x != nil {
		return x.AllocatePty
	}
	return false
}

func (x *CommandRequest) GetPtySize() *TerminalSize {
	if x != nil {
		return x.PtySize
	}
	return nil
}

func (x *CommandRequest) GetStdinData() []byte {
	if x != nil {
		return x.StdinData
	}
	return nil
}

// Command execution response
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`                   // Execution identifier
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                              // Whether command started
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error if not successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_bdrun_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdrun_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_bdrun_proto_rawDescGZIP(), []int{2}
}

func (x *CommandResponse) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Stream data (stdout/stderr/stdin)
type StreamData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`             // Execution identifier
	Stream        StreamType             `protobuf:"varint,2,opt,name=stream,proto3,enum=bdrun.v1.StreamType" json:"stream,omitempty"` // Which stream
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                               // Binary data
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`                                // End of stream marker
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamData) Reset() {
	*x = StreamData{}
	mi := &file_proto_bdrun_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamData) ProtoMessage() {}

func (x *StreamData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdrun_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamData.ProtoReflect.Descriptor instead.
func (*StreamData) Descriptor() ([]byte, []int) {
	return file_proto_bdrun_proto_rawDescGZIP(), []int{3}
}

func (x *StreamData) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *StreamData) GetStream() StreamType {
	if x != nil {
		return x.Stream
	}
	return StreamType_STREAM_UNKNOWN
}

func (x *StreamData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamData) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

// Terminal size for PTY
type TerminalSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	WidthPx       uint32                 `protobuf:"varint,3,opt,name=width_px,json=widthPx,proto3" json:"width_px,omitempty"`
	HeightPx      uint32                 `protobuf:"varint,4,opt,name=height_px,json=heightPx,proto3" json:"height_px,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSize) Reset() {
	*x = TerminalSize{}
	mi := &file_proto_bdrun_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSize) ProtoMessage() {}

func (x *TerminalSize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdrun_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSize.ProtoReflect.Descriptor instead.
func (*TerminalSize) Descriptor() ([]byte, []int) {
	return file_proto_bdrun_proto_rawDescGZIP(), []int{4}
}

func (x *TerminalSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *TerminalSize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalSize) GetWidthPx() uint32 {
	if x != nil {
		return x.WidthPx
	}
	return 0
}

func (x *TerminalSize) GetHeightPx() uint32 {
	if x != nil {
		return x.HeightPx
	}
	return 0
}

// PTY resize notification
type PTYResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Size          *TerminalSize          `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYResize) Reset() {
	*x = PTYResize{}
	mi := &file_proto_bdrun_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYResize) ProtoMessage() {}

func (x *PTYResize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdrun_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYResize.ProtoReflect.Descriptor instead.
func (*PTYResize) Descriptor() ([]byte, []int) {
	return file_proto_bdrun_proto_rawDescGZIP(), []int{5}
}

func (x *PTYResize) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *PTYResize) GetSize() *TerminalSize {
	if x != nil {
		return x.Size
	}
	return nil
}

// Exit code notification
type ExitCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitCode) Reset() {
	*x = ExitCode{}
	mi := &file_proto_bdrun_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitCode) ProtoMessage() {}

func (x *ExitCode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdrun_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitCode.ProtoReflect.Descriptor instead.
func (*ExitCode) Descriptor() ([]byte, []int) {
	return file_proto_bdrun_proto_rawDescGZIP(), []int{6}
}

func (x *ExitCode) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ExitCode) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// Error message
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_bdrun_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdrun_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_bdrun_proto_rawDescGZIP(), []int{7}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// Authentication request
type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthType      string                 `protobuf:"bytes,1,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"` // e.g., "token", "mutual-tls"
	Credentials   []byte                 `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`           // Type-specific credentials
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Optional client identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_proto_bdrun_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdrun_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_bdrun_proto_rawDescGZIP(), []int{8}
}

func (x *AuthRequest) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *AuthRequest) GetCredentials() []byte {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *AuthRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Authentication response
type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authenticated bool                   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"` // Assigned connection ID
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error if not authenticated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_bdrun_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdrun_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_bdrun_proto_rawDescGZIP(), []int{9}
}

func (x *AuthResponse) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *AuthResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *AuthResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_bdrun_proto protoreflect.FileDescriptor

const file_proto_bdrun_proto_rawDesc = "" +
	"\n" +
	"\x11proto/bdrun.proto\x12\bbdrun.v1\"\x89\x02\n" +
	"\aMessage\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.bdrun.v1.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12;\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1f.bdrun.v1.Message.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x02\n" +
	"\x0eCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x123\n" +
	"\x03env\x18\x03 \x03(\v2!.bdrun.v1.CommandRequest.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12!\n" +
	"\fallocate_pty\x18\x05 \x01(\bR\vallocatePty\x121\n" +
	"\bpty_size\x18\x06 \x01(\v2\x16.bdrun.v1.TerminalSizeR\aptySize\x12\x1d\n" +
	"\n" +
	"stdin_data\x18\a \x01(\fR\tstdinData\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x0fCommandResponse\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"y\n" +
	"\n" +
	"StreamData\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12,\n" +
	"\x06stream\x18\x02 \x01(\x0e2\x14.bdrun.v1.StreamTypeR\x06stream\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\"n\n" +
	"\fTerminalSize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x19\n" +
	"\bwidth_px\x18\x03 \x01(\rR\awidthPx\x12\x1b\n" +
	"\theight_px\x18\x04 \x01(\rR\bheightPx\"P\n" +
	"\tPTYResize\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12*\n" +
	"\x04size\x18\x02 \x01(\v2\x16.bdrun.v1.TerminalSizeR\x04size\"7\n" +
	"\bExitCode\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"\xa9\x01\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x126\n" +
	"\adetails\x18\x03 \x03(\v2\x1c.bdrun.v1.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\vAuthRequest\x12\x1b\n" +
	"\tauth_type\x18\x01 \x01(\tR\bauthType\x12 \n" +
	"\vcredentials\x18\x02 \x01(\fR\vcredentials\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"~\n" +
	"\fAuthResponse\x12$\n" +
	"\rauthenticated\x18\x01 \x01(\bR\rauthenticated\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage*\xd5\x01\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x13\n" +
	"\x0fCOMMAND_REQUEST\x10\x01\x12\x14\n" +
	"\x10COMMAND_RESPONSE\x10\x02\x12\x0f\n" +
	"\vSTDOUT_DATA\x10\x03\x12\x0f\n" +
	"\vSTDERR_DATA\x10\x04\x12\x0e\n" +
	"\n" +
	"STDIN_DATA\x10\x05\x12\x0e\n" +
	"\n" +
	"PTY_RESIZE\x10\x06\x12\r\n" +
	"\tEXIT_CODE\x10\a\x12\t\n" +
	"\x05ERROR\x10\b\x12\r\n" +
	"\tHEARTBEAT\x10\t\x12\x10\n" +
	"\fAUTH_REQUEST\x10\n" +
	"\x12\x11\n" +
	"\rAUTH_RESPONSE\x10\v*X\n" +
	"\n" +
	"StreamType\x12\x12\n" +
	"\x0eSTREAM_UNKNOWN\x10\x00\x12\x11\n" +
	"\rSTREAM_STDOUT\x10\x01\x12\x11\n" +
	"\rSTREAM_STDERR\x10\x02\x12\x10\n" +
	"\fSTREAM_STDIN\x10\x03B,Z*github.com/aard-fi/bdrun/internal/protocolb\x06proto3"

var (
	file_proto_bdrun_proto_rawDescOnce sync.Once
	file_proto_bdrun_proto_rawDescData []byte
)

func file_proto_bdrun_proto_rawDescGZIP() []byte {
	file_proto_bdrun_proto_rawDescOnce.Do(func() {
		file_proto_bdrun_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bdrun_proto_rawDesc), len(file_proto_bdrun_proto_rawDesc)))
	})
	return file_proto_bdrun_proto_rawDescData
}

var file_proto_bdrun_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_bdrun_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_bdrun_proto_goTypes = []any{
	(MessageType)(0),        // 0: bdrun.v1.MessageType
	(StreamType)(0),         // 1: bdrun.v1.StreamType
	(*Message)(nil),         // 2: bdrun.v1.Message
	(*CommandRequest)(nil),  // 3: bdrun.v1.CommandRequest
	(*CommandResponse)(nil), // 4: bdrun.v1.CommandResponse
	(*StreamData)(nil),      // 5: bdrun.v1.StreamData
	(*TerminalSize)(nil),    // 6: bdrun.v1.TerminalSize
	(*PTYResize)(nil),       // 7: bdrun.v1.PTYResize
	(*ExitCode)(nil),        // 8: bdrun.v1.ExitCode
	(*Error)(nil),           // 9: bdrun.v1.Error
	(*AuthRequest)(nil),     // 10: bdrun.v1.AuthRequest
	(*AuthResponse)(nil),    // 11: bdrun.v1.AuthResponse
	nil,                     // 12: bdrun.v1.Message.MetadataEntry
	nil,                     // 13: bdrun.v1.CommandRequest.EnvEntry
	nil,                     // 14: bdrun.v1.Error.DetailsEntry
}
var file_proto_bdrun_proto_depIdxs = []int32{
	0,  // 0: bdrun.v1.Message.type:type_name -> bdrun.v1.MessageType
	12, // 1: bdrun.v1.Message.metadata:type_name -> bdrun.v1.Message.MetadataEntry
	13, // 2: bdrun.v1.CommandRequest.env:type_name -> bdrun.v1.CommandRequest.EnvEntry
	6,  // 3: bdrun.v1.CommandRequest.pty_size:type_name -> bdrun.v1.TerminalSize
	1,  // 4: bdrun.v1.StreamData.stream:type_name -> bdrun.v1.StreamType
	6,  // 5: bdrun.v1.PTYResize.size:type_name -> bdrun.v1.TerminalSize
	14, // 6: bdrun.v1.Error.details:type_name -> bdrun.v1.Error.DetailsEntry
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_bdrun_proto_init() }
func file_proto_bdrun_proto_init() {
	if File_proto_bdrun_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bdrun_proto_rawDesc), len(file_proto_bdrun_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bdrun_proto_goTypes,
		DependencyIndexes: file_proto_bdrun_proto_depIdxs,
		EnumInfos:         file_proto_bdrun_proto_enumTypes,
		MessageInfos:      file_proto_bdrun_proto_msgTypes,
	}.Build()
	File_proto_bdrun_proto = out.File
	file_proto_bdrun_proto_goTypes = nil
	file_proto_bdrun_proto_depIdxs = nil
}
